version: "3.9"

services:
  web:
    build: .
    image: medirisk
    container_name: thoracic_predictions
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=5000
      - FLASK_DEBUG=True
      - MONGO_URI=mongodb+srv://kiran:kiranupputuru@cluster0.wygzu98.mongodb.net/thoracic_surgery_db?retryWrites=true&w=majority
      - JWT_SECRET_KEY=your_very_secure_secret_key_change_this_in_production
      - SECRET_KEY=your_flask_secret_key_here
    volumes:
      - .:/app
      - ./static:/app/static
      - ./static/images:/app/static/images
    ports:
      - "5000:5000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge