services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: cancer_prediction 
    container_name: thoracic_surgery_predictions
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=5000
      - FLASK_DEBUG=True
      - MONGO_URI=mongodb+srv://kiran:kiranupputuru@cluster0.wygzu98.mongodb.net/thoracic_surgery_db?retryWrites=true&w=majority
      - JWT_SECRET_KEY=your_very_secure_secret_key_change_this_in_production
      - SECRET_KEY=your_flask_secret_key_here
    volumes:
      - ./static:/app/static:rw
    ports:
      - "5000:5000"